"""create user table

Revision ID: 7a855034c4f7
Revises: 
Create Date: 2023-07-04 17:22:11.118735

"""

# revision identifiers, used by Alembic.
revision = "7a855034c4f7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
