"""add test field

Revision ID: a9eff599fc51
Revises: 7a855034c4f7
Create Date: 2023-07-04 17:45:27.007594

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a9eff599fc51"
down_revision = "7a855034c4f7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("intents", sa.Column("test_field", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("intents", "test_field")
    # ### end Alembic commands ###
